version: '3'
services:

  webserver:
    container_name: webserver
    image: adrianoapi/docker-laravel
    volumes:
      - ./app:/app
    links:
      - database
    ports:
      - 8080:80
    networks: 
    - laravel-network

  database:
    container_name: database
    restart: always
    image: postgres:alpine
    ports:
      - 54321:5432
    environment:
        POSTGRES_DB: homestead
        POSTGRES_USER: homestead
        POSTGRES_PASSWORD: secret
    volumes:
      - ./database:/var/lib/postgresql
    networks: 
    - laravel-network

networks: 
    laravel-network:
        driver: bridge